
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: mohamedmasry

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: mohamedmasry
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: mohamedmasry
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: mohamedmasry
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
