---
- name: Configure Web Servers
  hosts: webservers
  become: yes
  vars:
    web_server: apache # Change to 'nginx' to configure Nginx
    firewall_allowed_ports:
      - 80
      - 443
    sample_website_content: |
      <!DOCTYPE html>
      <html>
      <head>
        <title>Sample Website</title>
      </head>
      <body>
        <h1>Welcome to the Sample Website</h1>
      </body>
      </html>

  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
      when: web_server == 'apache'

    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
      when: web_server == 'nginx'

    - name: Ensure Apache service is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes
      when: web_server == 'apache'

    - name: Ensure Nginx service is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
      when: web_server == 'nginx'

    - name: Deploy sample website for Apache
      copy:
        content: "{{ sample_website_content }}"
        dest: /var/www/html/index.html
      when: web_server == 'apache'

    - name: Deploy sample website for Nginx
      copy:
        content: "{{ sample_website_content }}"
        dest: /var/www/html/index.nginx-debian.html
      when: web_server == 'nginx'

    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present

    - name: Allow necessary ports through the firewall
      ufw:
        rule: allow
        port: "{{ item }}"
      with_items: "{{ firewall_allowed_ports }}"

    - name: Enable UFW
      ufw:
        state: enabled
        policy: allow
